# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(803, 713)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(40, 90, 352, 171))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout_2.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.TileSize = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.TileSize.setMaximum(100000)
        self.TileSize.setProperty("value", 512)
        self.TileSize.setObjectName("TileSize")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.TileSize)
        self.label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label)
        self.ModelComboBox = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.ModelComboBox.setObjectName("ModelComboBox")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.ModelComboBox)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_2)
        self.InputImageButton = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.InputImageButton.setObjectName("InputImageButton")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.InputImageButton)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_3)
        self.StartInferenceButton = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.StartInferenceButton.setObjectName("StartInferenceButton")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.StartInferenceButton)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_4)
        self.ImageBrowser = QtWidgets.QGraphicsView(self.centralwidget)
        self.ImageBrowser.setGeometry(QtCore.QRect(400, 40, 321, 251))
        self.ImageBrowser.setObjectName("ImageBrowser")
        self.ImageBrowserOut = QtWidgets.QGraphicsView(self.centralwidget)
        self.ImageBrowserOut.setGeometry(QtCore.QRect(400, 320, 321, 251))
        self.ImageBrowserOut.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.ImageBrowserOut.setObjectName("ImageBrowserOut")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 360, 231, 211))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.textBrowser = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 803, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Размер тайла"))
        self.label_2.setText(_translate("MainWindow", "Модель"))
        self.InputImageButton.setText(_translate("MainWindow", "Выберите изображение"))
        self.label_3.setText(_translate("MainWindow", "Выбор изображения"))
        self.StartInferenceButton.setText(_translate("MainWindow", "Начать"))
        self.label_4.setText(_translate("MainWindow", "Запуск инференса"))
        self.label_6.setText(_translate("MainWindow", "Значение метрик"))
